const products = [
  {
    id: 0,
    prodid: "officepackage1",
    prodtitle: "Office Package no.1",
    proddesc: ["AMD Ryzen 3 4100 CPU 4 Core", "B450M PRO-VDH MAX - MSI B450M PRO-VDH MAX AM4 Motherboard", "Intergrated onboard graphics", "16GB DDR4 Memory", "1TB Gen4 NVMe SSD Hard Drive", "Antec Black Case", "500W power Supply", "Windows 11 Pro"],
    prodprice: "800.00",
    prodpercentoff: "",
    prodcat: "1",
    prodimage: "/products/office1.jpg",
    },
  {
    id: 1,
    prodid: "sysgi530501t32",
    prodtitle: "Guardian Gaming PC 32G",
    proddesc: ["Intel Core i5 12400F 12th Gen 6 Core CPU", "Asus or MSI H610M Motherboard with Wifi", "Asus or MSI RTX3050 6G OC Video card", "Gskill or Corsair 32GB DDR4 Memory", "Crucial or similar 1TB Gen4 NVMe SSD Hard Drive", "Cougar Archon 2 Mesh Airflow Gaming Case with 3x ARGB Fans  (White colour available - Please request as required)", "Cougar or MSI 600W ATC 80+ Bronze PSU", "Windows installation (if purchased with system)"],
    prodprice: "1350.00",
    prodpercentoff: "10",
    prodcat: "1",
    prodimage: "/products/guardiangamingpc32g.jpg",
    },
  {
    id: 2,
    prodid: "GARTX5090MV30",
    prodtitle: "GeForce RTX 5090 32G VENTUS 3X OC",
    proddesc: ["MSI GeForce RTX 5090 32G VENTUS 3X OC RTX5090 Video card"],
    prodprice: "6950.00",
    prodpercentoff: "5",
    prodcat: "4",
    prodimage: "/products/gartx5090mv30.jpg",
    },
  {
    id: 3,
    prodid: "GARTX5090ATO",
    prodtitle: "AUS TUFF Gaming RTX 5090 O32G",
    proddesc: ["Asus TUF-RTX5090-O32G-GAMING RTX5090 Video Card"],
    prodprice: "7270.00",
    prodpercentoff: "",
    prodcat: "4",
    prodimage: "/products/gartx5090ato.jpg",
    },
  {
    id: 4,
    prodid: "MSIGF40803X",
    prodtitle: "MSI GEFORCE RTX 4080 16GB",
    proddesc: ["MSI GEFORCE RTX 4080 16GB VENTUS 3X OC"],
    prodprice: "7270.00",
    prodpercentoff: "",
    prodcat: "4",
    prodimage: "/products/msigf40803x.png",
    },
];
export default products;